pip install requests
pip install websocket-client
pip install tls-client
pip install customtkinter
pip install typing_extensions
pip install tkinter
pip install pycryptodome
pip install toml
pip install twocaptcha